### ISSUE TITLE
CSP error

### ISSUE THREAD

**Issue by tvdijen** [OpenConext/Stepup-RA#161]
`Aug 14 18:58:33 webapp-1 RA[7339]: {"channel":"security","level":"NOTICE","message":"Content-Security-Policy Violation Reported","context":{"csp-report":{"blocked-uri":"","document-uri":"https://ra.stepup.moo-archive.nl/authentication/consume-assertion","original-policy":"default-src https://ra.stepup.moo-archive.nl; report-uri https://ra.stepup.moo-archive.nl/csp/report","referrer":"https://gateway.stepup.moo-archive.nl/verify-second-factor/yubikey","script-sample":"onfocusin attribute on DIV element","source-file":"https://ra.stepup.moo-archive.nl/authentication/consume-assertion","violated-directive":"default-src"}},"extra":{"server":"ra.stepup.moo-archive.nl","application":"registration-authority","request_id":"e8df3245ef15dfe3978d0cacea998ced"}}`

**Comment by MKodde** [comment]
Thanks for the report @tvdijen. I'm going to try to reproduce this, do you have this issue in all major browsers? Or just in one/some of them? And looking at the report this occurs when giving a second factor using the Yubikey token during authenticating for the RA environment right?

From the top of my head, this looks like a false positive CPS report I've come across before that was triggered by using either the Symfony toolbar or some developer toolbar browser extension (can't accurately recall right now).

**Comment by tvdijen** [comment]
I had this issue when using Yubikey as a second factor to login to the RA, yes.
I haven't realised it would be browser-dependent, but I've been using Firefox when this happened and I can try some other browsers if you want..

I've tried to investigate the "onfocusin attribute on DIV element" and noticed that the included JS dies some 'focusin'-calls.. That's when I decided to open an issue.

**Comment by tvdijen** [comment]
I can confirm this is a Firefox-only issue... I have, however, no add-ons installed other than SAMLtracer

**Comment by pmeulen** [comment]
Not my cup of tea either. I've sent some time looking into this, but this has not proven a simple one to track down. In release 15 logging of CSP reports was fixed. We also added some logstash parsing to help figure out what's going on (https://github.com/OpenConext/Stepup-Deploy/blob/develop/roles/manage/templates/logstash/20-symfony.conf.j2#L85). 

What we see in production logging is that Firefox CSP reports are over represented, but we get them from safari, chrome, edge as well. The CSP policy is enforce everywhere, but the applications remain functional (or users do not complain). The CSP reports I get personally are due to firefox plugins. 

To put things into perspective, per 1000 authentications we see in production to the Stepup-Gateway, about 20 CSP violations are logged by all the Stepup applications together.

I'm afraid that if you want to reduce the CSP reports, you'll have to look at them one by one and try to figure out why each of them happens. If a Stepup application is to blame, by bet it is because of the included JS/CSS (e.g. jquery, bootstrap).

**Comment by tvdijen** [comment]
Yeah, all the included CSS/JS packages are pretty old...
I've tried updating mopa-bootstrap, but even the slightest update from 3.0.0-RC2 to 3.0.0 horribly breaks one of the generated CSS-files (file almost empty)

**Comment by MKodde** [comment]
That's a bummer! Updating these dependencies is on my radar but does not have super high priority at the moment. Maybe we can work together on this one? I'll investigate the Mopa Bootstrap bundle issue and maybe you can focus on upgrading the other packages.

**Comment by tvdijen** [comment]
I’ll see how far I can get!!

**Comment by tvdijen** [comment]
I think as a first step, this would be a feasible set of dependencies, but only if you can figure out why Mopa is breaking the generated css-files:
https://github.com/tvdijen/Stepup-RA/commit/8d133d31ffe4b46d06797a317c9743f8e1a9ed71

Then, as a second step, Symfony can be upgraded to 3.0 and we can get rid of the abandoned symfony/assetic-bundle in favor of symfony/webpack-encore-pack.

Btw, I had a similar issue with the corrupted css when upgrading twbs/bootstrap to 4.x...

**Comment by pmeulen** [comment]
Stepup-SelfService and Stepup-Gateway are similar to Stepup-RA, so what we learn here should also apply to those components. We'll need to update to a new LTS Symfony. It is good to know whether there a sensible way to update CSS/JS frameworks without doing a Symfony update.

Related pivotal issues: https://www.pivotaltracker.com/story/show/159822458 and https://www.pivotaltracker.com/story/show/159922215

**Comment by MKodde** [comment]
I've been brainstorming with @pablothedude today and we consider pulling the Symfony & frontend build tooling in our current sprint. And we indeed intend to fix for all Stepup applications in one go.

And it would still be possible to update our frontend dependencies without upgrading Symfony. The choice for the Mopa Bootstrap bundle, however, ties us to their upgrade path and that is somewhat limiting.
